server:
  port: 8080
  servlet:
    context-path: /kicks-hub-service

spring:
  application:
    name: kicks-hub-service
  datasource:
    url: "jdbc:mysql://localhost:3307/kicks_hub"
    username: root
    password: 171104
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud_name: "dcudlkqcm"
  api_key: "734251979716821"
  api_secret: "WHzx_91QpnZwhLi0DOrxJGMJDT4"